services:
  valhalla:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: neartime-valhalla
    restart: unless-stopped

    ports:
      - "127.0.0.1:8002:8002"

    volumes:
      - ./valhalla-data:/custom_files

    environment:
      - tile_urls=https://download.geofabrik.de/europe/norway-latest.osm.pbf
      - server_threads=4
      - serve_tiles=True
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - build_transit=False
      - build_tar=True
      - force_rebuild=False
      - update_existing_config=True
      - use_tiles_ignore_pbf=False